name: CI workflow

on:
  push:
    branches:
      - main
env:
  NODE_VERSION: 22.0.0
jobs:
  cd:
    runs-on: ubuntu-latest
    name: Build and publish docker
    steps:
      - uses: actions/checkout@v5
      - name: Build docker
        run: docker build -t my-image:latest .
      - name: Echo docker
        run: docker image list
